from __future__ import annotations

from typing import Protocol, runtime_checkable

from models.entities import Book, Loan, Reservation, User


@runtime_checkable
class IUserRepository(Protocol):
    def get_by_id(self, user_id: str) -> User | None: ...
    def save(self, user: User) -> None: ...
    def list_all(self) -> list[User]: ...


@runtime_checkable
class IBookRepository(Protocol):
    def get_by_id(self, book_id: str) -> Book | None: ...
    def save(self, book: Book) -> None: ...
    def list_all(self) -> list[Book]: ...


@runtime_checkable
class ILoanRepository(Protocol):
    def get_by_id(self, loan_id: str) -> Loan | None: ...
    def save(self, loan: Loan) -> None: ...
    def list_by_user(self, user_id: str) -> list[Loan]: ...
    def list_by_book(self, book_id: str) -> list[Loan]: ...
    def list_active_by_user(self, user_id: str) -> list[Loan]: ...
    def list_active_all(self) -> list[Loan]: ...


@runtime_checkable
class IReservationRepository(Protocol):
    def get_by_id(self, reservation_id: str) -> Reservation | None: ...
    def save(self, reservation: Reservation) -> None: ...
    def delete(self, reservation_id: str) -> None: ...
    def queue_for_book(self, book_id: str) -> list[Reservation]: ...
    def has_user_pending(self, user_id: str, book_id: str) -> bool: ...
    def next_sequence(self) -> int: ...
